### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by aurkaxi** [FT-Labs/PhySettings#2]
i use picom fork. not the whole iso. Can i install it? How?

**Comment by r0-zero** [comment]
Just get this repo, then make && sudo make install to install tui app

**Comment by aurkaxi** [comment]
```
❯ make
GOOS=linux GOARCH=amd64 go build -o physettings main.go
❯ sudo make install
[sudo] password for ashroy:
mkdir -p /usr/bin
cp -f physettings /usr/bin
chmod 755 /usr/bin/physettings
❯ physettings
panic: Can't open user settings file

goroutine 1 [running]:
github.com/FT-Labs/physettings/utils.FetchAttributes()
	/home/ashroy/Softwares/physettings/utils/utils.go:148 +0x965
main.main()
	/home/ashroy/Softwares/physettings/main.go:24 +0x2e
```

**Comment by r0-zero** [comment]
```
#!/bin/bash

PLYMOUTH=true
POWERMENU_TYPE=
POWERMENU_STYLE=
POWERMENU_CONFIRM=true
PICOM_EXPERIMENTAL=
```

Could you copy this file to ``` ~/.config/phyos/phyos.conf ```

**Comment by aurkaxi** [comment]
same error

**Comment by r0-zero** [comment]
It shouldnt be, are you sure path is correct

**Comment by r0-zero** [comment]
Could you please duplicate the file in here 
~/.config/phyos/phyos.conf.default

**Comment by aurkaxi** [comment]
uh umm sorry that was different error just looked same:
```
panic: Can't open default settings file

goroutine 1 [running]:
github.com/FT-Labs/physettings/utils.FetchAttributes()
	/home/ashroy/Softwares/physettings/utils/utils.go:174 +0x931
main.main()
	/home/ashroy/Softwares/physettings/main.go:24 +0x2e
```

after duplication in phyos.conf.default it says:
```
panic: Can't fetch script data

goroutine 1 [running]:
github.com/FT-Labs/physettings/utils.fetchScriptInfo()
	/home/ashroy/Softwares/physettings/utils/utils.go:100 +0x1c8
github.com/FT-Labs/physettings/utils.FetchAttributes()
	/home/ashroy/Softwares/physettings/utils/utils.go:199 +0x7aa
main.main()
	/home/ashroy/Softwares/physettings/main.go:24 +0x2e
```

**Comment by r0-zero** [comment]
Oh okay im writing the dependencies. If you are using arch I can tell a much more simple way btw.

https://github.com/FT-Labs/phyOS-system-scripts/blob/master/usr/share/man/man1/phyos.1

Download this man file and put it to /usr/share/man/man1/

Download this python script and put it to /usr/local/bin
Please chmod +x it make it executable
https://github.com/FT-Labs/phyOS-sysconf/blob/master/usr/local/bin/manfilter

**Comment by aurkaxi** [comment]
Thanks, it's working.
